const express = require("express");
const router = express.Router();
const rides = require("../rest/controllers/rides");
router.post("/request", rides.requestRide);
router.get("/", rides.listRides);
router.patch("/:id/accept", rides.acceptRide);
router.patch("/:id/start", rides.startRide);
router.patch("/:id/complete", rides.completeRide);
router.patch("/:id/cancel", rides.cancelRide);
module.exports = router;
